### PR TITLE
fix: proper date and media folder for exports

### LINKED ISSUE #1054: Data Export - File Naming - Observations + Media
https://www.notion.so/digidem/Data-Export-File-testing-2101b08162d580fcbefbd856b4daaf27

It is currently as:
Folder title : **CoMapeo_Forest project_Obsvns_Tracks_Thu Jun 12 2025.zip**
File title : **CoMapeo_Forest project_Obsvns_Tracks_Thu Jun 12 2025.geojson**
Folder title with media : **[object Promise]** + **original**

It should be listed as:

- Folder title : CoMapeo_[Project Name]_Obsvns_YYYY-MM-DD.zip
- File title : CoMapeo_[Project Name]_Obsvns_YYYY-MM-DD.geojson
- Folder title with media : CoMapeo_[Project Name]_Obsvns_YYYY-MM-DD_Media
- Missing attachment file name : Log of missing data.txt

### PR DESCRIPTION
**Pull request by RangerMauve**
closes #1054

### CODE REVIEW

File: src/mapeo-project.js [hunk 1]
```diff
@@ -973,15 +973,12 @@ export class MapeoProject extends TypedEmitter {
...
-        year: 'numeric',
-        month: 'numeric',
-        day: 'numeric',
-      })
-      .replaceAll('/', '_')
-      .replaceAll('-', '_')
-    return `CoMapeo_${name}_${type}_${dateSection}`
+    const yyyy = date.getFullYear()
+    const _mm = date.getMonth() + 1
+    const mm = _mm < 10 ? `0${_mm}` : _mm.toString()
```
Comment (gmaclennan) [inline src/mapeo-project.js:978]:
```suggestion
    const mm = `${date.getMonth() + 1}`.padStart(2, '0')
```

File: src/mapeo-project.js [hunk 2]
```diff
@@ -973,15 +973,12 @@ export class MapeoProject extends TypedEmitter {
...
+    const _dd = date.getDate()
+    const dd = _dd < 10 ? `0${_dd}` : _dd.toString()
```
Comment (gmaclennan) [inline src/mapeo-project.js:980]:
```suggestion
    const dd = `${date.getDate()}`.padStart(2, '0')
```

**Review by gmaclennan — APPROVED** [review]
approved, although you could switch your custom `padLeft()` implementation for the built-in
